### ISSUE TITLE
Custom spinner loading parameter

### ISSUE THREAD

**Issue by alfrejivi** [ooyala/html5-skin#434]
I was doing some tests with player v4 and I wanted to change the "spinner loading" image and I realized that I need to modify directly the "js/components/spinner.js" file.
In my opinion it would be much better be able to modify this from the "skin config json" file that it was that I was searching on the documentation.

**Comment by ksunika** [comment]
you are absolutely right, and we already made the changes (though not in stable yet).
Look for general -> loadingImage in 
https://github.com/ooyala/skin-config/blob/e23c1c523074fc3d82984a54c894590446044216/skin.json

**Comment by alfrejivi** [comment]
thank you! it's much better now
