### ISSUE TITLE
Watermark clickthrough not working

### ISSUE THREAD

**Issue by AndersenJ** [ooyala/html5-skin#482]
The use of a watermark clickUrl as documented [here](http://support.ooyala.com/documentation/reference/faq_pbv4.html) and [here](https://github.com/ooyala/skin-config/blob/master/skin.json) does not work. It simply does not turn the watermark into a link.

Using /v4/latest/

As a sidenote, why is it called a watermark when it is actually an icon and not at all a watermark?

**Comment by mistermendez** [comment]
Great feedback, see update - #500
