### ISSUE TITLE
Overrides Should Use Deep Merge

### ISSUE THREAD

**Issue by delianides** [ooyala/html5-skin#579]
When you specify overrides through json and pass the parameters through `createPlayer` you have to define the entire base object or you get an error. For example: 

If I wanted to change a button I couldn't do:

```
"buttons":{
   "desktopContent": [
       {"name": "playPause", "location":"moreOptions", "whenDoesNotFit":"drop", "minWidth": 45 }
     ]
}
```

Instead I have to include the whole button object as defined in the schema just to change one option. If you utilize Object.assign you can drastically cut down on the amount of JSON that has to be included when a developer wants to override a particular setting. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by mistermendez** [comment]
hi @delianides, we are [using deep merge](https://github.com/ooyala/html5-skin/blob/stable/js/controller.js#L231). The example you have above works with the following params. Sorry for late reply.

```
var playerParam = {
    "pcode": "5zb2wxOlZcNCe_HVT3a6cawW298X",
    "playerBrandingId": "26e2e3c1049c4e70ae08a242638b5c40",
    'debug':false,
    "skin": {
      "config": "",
      "inline": {"shareScreen": {"embed": {"source": "<iframe width='640' height='480' frameborder='0' allowfullscreen src='//player.ooyala.com/static/v4/stable/latest/skin-plugin/iframe.html?ec=<ASSET_ID>&pbid=<PLAYER_ID>&pcode=<PUBLISHER_ID>'></iframe>"}},
        "buttons":{
          "desktopContent": [
            {"name": "playPause", "location":"moreOptions", "whenDoesNotFit":"drop", "minWidth": 45 }
          ]
        }}
    }
  };
```

**Comment by mistermendez** [comment]
resolved with - https://github.com/ooyala/html5-skin/pull/693
