### ISSUE TITLE
Closed captions changed via player javascript api does not change the skin state

### ISSUE THREAD

**Issue by naeem91** [ooyala/html5-skin#676]
I've recently came across this issue. When the player's closed captions language is changed via javaScript api method [setClosedCaptionsLanguage](http://apidocs.ooyala.com/player_v4_js/OO.Player.html#setClosedCaptionsLanguage), that does change the running cc language but does not update the skin's state. 

As a result:
- the new selected language is not reflected in CC language tab
-  The language change reverts when any skin event re-triggers the skin's setClosedCaptionsLanguage method and sets the language back to the stored language. 

The problem is due to the fact that OO.EVENTS.SET_CLOSED_CAPTIONS_LANGUAGE is not subscribed in the skin code to update the internal state.

**Comment by mistermendez** [comment]
Thanks for the feedback. Fixed in PR https://github.com/ooyala/html5-skin/pull/708

**Comment by naeem91** [comment]
Thank you.
