### ISSUE TITLE
Use Skin.defaultProps instead of a http request to a skin.json

### ISSUE THREAD

**Issue by frankinedinburgh** [ooyala/html5-skin#699]
I want to define all my parameter settings for the player skin in my ```4.8.5/js/skin.js``` file in this repo but I am unable to get the values unless I give a value to the below parameter. 
```js
skin: {
 config: ''
}
```

Is there a way I can load the the defaultProps from skin.js instead of using the default process of getting the skin.json file. I want everything defined in the html5-skin instead of making an api call to the json file. Can someone point me in the right direction.

Much obliged

**Comment by mistermendez** [comment]
we made that update in [this PR #671](https://github.com/ooyala/html5-skin/pull/671), try latest version of html5-skin. The skin.json file is bundled with app and no longer uses API call.

https://github.com/ooyala/html5-skin/blob/stable/sample.html#L22

**Comment by frankinedinburgh** [comment]
Thanks Mistermendez
