### ISSUE TITLE
Self Hosting Player 

### ISSUE THREAD

**Issue by frankinedinburgh** [ooyala/html5-skin#722]
Hi there, 

I use to be able to self host the player files on my own server, using version 4.8.5. The issue I noticed with player 4.11.13 is that the bit_wrapper plugin fails to work on chrome and firefox when I self host. I have no issues with safari. Should I be including another file ?
The files that have been included are:

-video-plugin
-- main_html5.min.js
-- bit_wrapper.min.js
-- bitmovin.swf
-- bitmovinplayer-core.min.css
-- bitmovinplayer-core.min.js

Thanks in advance

**Comment by ksunika** [comment]
@frankinedinburgh, the bitmovin lib files have different names in the new release. Please use the new files.

**Comment by frankinedinburgh** [comment]
When I go to the sample page and check out the network tab these are the files I find. Are these the correct ones ?
http://player.ooyala.com/static/v4/stable/4.11.13/video-plugin/bitmovinplayer-core.min.js
http://player.ooyala.com/static/v4/stable/4.11.13/video-plugin/bitmovinplayer-core.min.css
http://player.ooyala.com/static/v4/stable/4.11.13/video-plugin/bitmovinplayer.swf

**Comment by ksunika** [comment]
@frankinedinburgh, these three should be fine

**Comment by frankinedinburgh** [comment]
`This is the structure of the build folder


build
-- assets
-- config
-- skin-plugin
-- video-plugin
---- bit_wrapper.min.js
---- bitmovinplayer.min.js
---- bitmovinplayer.swf
---- bitmovinplayer-core.min.js
---- bitmovinplayer-core.min.css
---- main-html5.min.js
---- osmf_flash.min.js

core.min.js
amp_iframe.html
iframe.html`

When I host these files on S3 I am unable to get the bit_wrapper plugin to work in firefox or chrome. I have to use the ooyala cdn to make it work. Would it be possible to add a section in the README on instructions for self hosting ?

**Comment by ksunika** [comment]
Please read http://help.ooyala.com/video-platform/concepts/pbv4_host.html for self-hosing guidelines.
